/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HangmanGame {
    'text': string;
  }
}

declare global {


  interface HTMLHangmanGameElement extends Components.HangmanGame, HTMLStencilElement {}
  var HTMLHangmanGameElement: {
    prototype: HTMLHangmanGameElement;
    new (): HTMLHangmanGameElement;
  };
  interface HTMLElementTagNameMap {
    'hangman-game': HTMLHangmanGameElement;
  }
}

declare namespace LocalJSX {
  interface HangmanGame {
    'onCtaClick'?: (event: CustomEvent<any>) => void;
    'text'?: string;
  }

  interface IntrinsicElements {
    'hangman-game': HangmanGame;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'hangman-game': LocalJSX.HangmanGame & JSXBase.HTMLAttributes<HTMLHangmanGameElement>;
    }
  }
}


